name:hello-world
on: push
 push:
    branches: [ "develop" ]
jobs
    my-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
	- name: build
	  run: echo "Hello World!"
	
